### PR TITLE
Added a way to store result in specified variable without printing it

### PR DESCRIPTION
**Pull request by nurikk**
You can now do:

```
%%sql 
result <<
select 1
```
this will save result to `result` variable

and same for single lint

`%sql result << select 123`
is equal to
`result = %sql select 123`

### CODE REVIEW

**Comment by siyuwj** [comment]
This design is a little bizarre as the designing purpose of %sql is for fast data exploration. If you want to get result without displaying in your console or notebook, 

```python
o.execute_sql('select * from iris').open_reader().to_pandas()
```

may be a better solution.

What's more, there are risks trying to add **new features** into existing MaxCompute SQL syntax by hacking methods, as MaxCompute do accept queries like

```sql
select' <<' from dual;
```

So you may need a shortcut method such as to_pandas in Instance class instead of adding new features into %sql magic.

**Comment by nurikk** [comment]
@siyuwj I ported this syntax from 
https://github.com/catherinedevlin/ipython-sql#assignment

and this is not adding feature to _MaxCompute SQL_, this is adding feature to **sql magic**, this code will never affect nothing except ipython/jupiter

and this query works in any condition

image

**Comment by siyuwj** [comment]
I missed a space character in my example. The case

```sql
select' << ' from dual;
```

will result in a ParseError, thus breaking the existing behavior of MaxCompute SQL.

**Comment by chineking** [comment]
Agree with @siyuwj 

SQL in ipython-sql are basically standard SQL, meanwhile the MaxCompute SQL is actually new sql, and in the near future, a lot of new features will be brought to MaxCompute SQL, we should not do any **parse** job at client which may conflict with them.

```
r = %sql select * from dual;
```

is quite elegant, for multiple line sql, just get the N cell result through _N variable.

Overall, I think this feature will bring more overdesign than the real benefits.

Anyway, thank u for ur contribution all the same.

**Comment by nurikk** [comment]
@siyuwj @chineking I can move this logic to **cell magic** and parsy flags only from it, and skip it in *line magic*
image

**Comment by chineking** [comment]
My point is not whether we should parse  << only for multiple line SQL.

Once we try to split the user's SQL, it's sort of **parse** behavior, right?

It's fine for ANSI SQL, however, maybe some day << will become an internal operator of MaxCompute SQL which is not the standard SQL, who knows...

**Comment by nurikk** [comment]
I see. I will use 
`o.execute_sql('select * from iris').open_reader().to_pandas()`
or
`result = _`
That is sad, what we can't consider maxcompute sql like subset of standard sql :(

We can close pull request now

**Comment by chineking** [comment]
Thank u.

btw, I think the way below is quite acceptable for me.

```
In [11]: %%sql
    ...: select * from pyodps_iris limit 3;
    ...: 
Out[11]: 
   sepal_length  sepal_width  petal_length  petal_width     category
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa

In [12]: _11
Out[12]: 
   sepal_length  sepal_width  petal_length  petal_width     category
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
```

**Pull request closed without merging**
